repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --line-length 100
        language: python
        'types': [ python ]

      - id: prospector
        name: prospector
        entry: poetry run prospector --max-line-length 150
        language: python
        'types': [ python ]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: poetry run pytest -v -s
        language: python
        'types': [ python ]
        pass_filenames: false
