export const typewriterSentences = [
    'Wie finde ich den Vertragsentwurf für Kunde A?',
    'Wo ist der Baustellenplan für Kunde B?',
    'Was muss beim Umgang mit Kunde Y beachtet werden?',
    'Wie aktualisiere ich Kundenkontaktinformationen?',
    'Was sind die Lieferbedingungen für Lieferant B?',
    'Wo sehe ich die letzte Bestellung von Kunde A?',
    'Wo ist die Preisliste für Großkunden?',
    'Wie kann ich den aktuellen Angebotsstatus einsehen?',
    'Wo finde ich Kundenfeedback zu unserem Produkt?',
    'Wie prüfe ich die Kreditlimits unserer Kunden?',
    'Wo gibt es Dokumentation zu unserem ERP-System?',
    'Wie erfasse ich eine Reklamation?',
    'Wo finde ich eine Produktliste?',
    'Wo sind unsere Emailvorlagen?',
    'Wo finde ich die Lieferzeitenübersicht für unsere Produkte?',
    'Was sind die Zahlungsbedingungen für Lieferant C?',
    'Wo sind Verträge mit Kunden gespeichert?',
    'Wie sieht der Implementierungsplan für das neue CRM-System aus?',
    'Was ist der Prozess zur Bewertung neuer Lieferanten?',
    'Wie aktualisiere ich unsere Umsatzprognose?',
    'Wo finde ich die Richtlinien zum Umgang mit Kundendaten?',
    'Wie erstelle ich einen Bericht für die Geschäftsführung?',
    'Was ist der Eskalationsprozess bei Qualitätsproblemen?'
];
